import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";
import fs from "fs/promises";
import path from "path";

// eta imports node:fs and node:path for file-based template loading, which we never use.
// Strip those imports from eta's source at bundle time so they don't appear in the plugin bundle.
const stripEtaNodeDeps = {
  name: "strip-eta-node-deps",
  setup(build) {
    build.onLoad({ filter: /eta\/dist\/index\.mjs$/ }, async (args) => {
      const source = await fs.readFile(args.path, "utf8");
      const stripped = source
        .replace(/^import \* as fs from ["']node:fs["'];?\n?/m, "")
        .replace(/^import \* as path from ["']node:path["'];?\n?/m, "");
      return { contents: stripped, loader: "js" };
    });
  },
};

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

// Ensure dist directory exists
await fs.mkdir('dist', { recursive: true });

// Copy manifest.json to dist
await fs.copyFile('manifest.json', 'dist/manifest.json');

// Copy styles.css to dist
await fs.copyFile('styles.css', 'dist/styles.css');

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ['src/main.ts'],
    bundle: true,
    plugins: [stripEtaNodeDeps],
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...builtinModules,
        ...builtinModules.map((m) => `node:${m}`)],
    format: 'cjs',
    target: 'es2018',
    logLevel: "info",
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outfile: 'dist/main.js',
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
} 